# UNMANAGED, project-specific build wiring. This file is never regenerated by a
# template upgrade — it is the one place to evolve the package build and any
# custom checks.
#
# pgmq-hs builds from a ghc9124 package set extended with ONLY the project's
# local ./nix/haskell-overlay.nix (which provides the local pgmq-* packages and
# the git-pinned hasql / hs-opentelemetry / ephemeral-pg dependencies). It does
# NOT use the shared haskell-nix registry.
{ inputs, ... }:
{
  perSystem = { system, pkgs, ... }:
    let
      haskellPackages = pkgs.haskell.packages.ghc9124.override {
        overrides = import ./nix/haskell-overlay.nix { inherit pkgs; };
      };

      # Re-enable tests and inject PostgreSQL into PATH
      withTests = pkg:
        pkgs.haskell.lib.overrideCabal (pkgs.haskell.lib.doCheck pkg) (old: {
          testToolDepends = (old.testToolDepends or [ ]) ++ [ pkgs.postgresql ];
          preCheck = (old.preCheck or "") + ''
            export HOME=$(mktemp -d)
          '';
        });
    in
    {
      packages = {
        pgmq-core = haskellPackages.pgmq-core;
        pgmq-hasql = haskellPackages.pgmq-hasql;
        pgmq-effectful = haskellPackages.pgmq-effectful;
        pgmq-migration = haskellPackages.pgmq-migration;
        pgmq-config = haskellPackages.pgmq-config;
        default = haskellPackages.pgmq-hasql;
      };

      checks = {
        inherit (haskellPackages) pgmq-core pgmq-hasql pgmq-effectful pgmq-migration pgmq-config;
        pgmq-hasql-tests = withTests haskellPackages.pgmq-hasql;
        pgmq-migration-tests = withTests haskellPackages.pgmq-migration;
        pgmq-config-tests = withTests haskellPackages.pgmq-config;
      };
    };
}
